std_msgs/Header header

string dataset_path
string dataset_id
string slam_mode
bool multithreading
bool enable_visu
string optimizer
int32 contrast_enhancer
float32 clahe_clip
float32 downsampling
int32 marginalization
bool sparsification
string pose_estimator
string rel_pose_estimator
float32 eskf_r
string tracker
int32 min_kf_number
int32 max_kf_number
int32 fixed_frame_number
float32 min_lmk_number
float32 min_movement_parallax
float32 max_movement_parallax
bool mesh3d
float64 zncc_tsh
float64 max_length_tsh

SLAMFeatures[] features_handled