# SET(CMAKE_CONFIGURATION_TYPES Debug;Release;MinSizeRel;RelWithDebInfo)
SET(CMAKE_BUILD_TYPE DEBUG) # DEBUG / RELEASE

# set(CMAKE_BUILD_TYPE "DEBUG")
project(isae_slam)
cmake_minimum_required(VERSION 3.14)

list(APPEND CMAKE_MODULE_PATH "${${PROJECT_NAME}_SOURCE_DIR}/cmake")
include(CheckCXXCompilerFlag)
include(CheckLibraryExists)
include(GNUInstallDirs)
include(UpdateCacheVariable)

# -------------------------------------------------------------------
# Compiler Options
# -------------------------------------------------------------------
add_definitions("-Wall -std=c++17 -O3")

if(CMAKE_BUILD_TYPE STREQUAL "DEBUG")
  message(STATUS "Debug configuration")
  add_definitions("-g")
else(CMAKE_BUILD_TYPE STREQUAL "RELEASE")
  message(STATUS "Release configuration")
  add_definitions("-O3")
endif(CMAKE_BUILD_TYPE STREQUAL "DEBUG")

add_definitions(-D_USE_MATH_DEFINES)

# -------------------------------------------------------------------
# Dependencies
# -------------------------------------------------------------------
find_package(OpenCV REQUIRED)
find_package(Eigen3 REQUIRED)
find_package(yaml-cpp REQUIRED)
find_package(Ceres REQUIRED)
find_package(Boost REQUIRED COMPONENTS system)

include_directories(
  include
  ${OpenCV_INCLUDE_DIRS}
  ${EIGEN3_INCLUDE_DIR}
  ${CERES_INCLUDE_DIRS}
  ${YAML_CPP_INCLUDE_DIR}
)

# -------------------------------------------------------------------
# Library
# -------------------------------------------------------------------
file(GLOB_RECURSE LIB_SOURCES src/*.cpp include/*.cpp
  thirdparty/ELSED/src/*.cpp)
file(GLOB_RECURSE LIB_HEADERS include/*.h include/*.hpp include/*.inl
  thirdparty/ELSED/src/*.h)
add_library(${PROJECT_NAME} SHARED ${LIB_SOURCES} ${LIB_HEADERS})
target_link_libraries(${PROJECT_NAME} ${OpenCV_LIBS} ${CERES_LIBRARIES} ${YAML_CPP_LIBRARIES} ${Boost_SYSTEM_LIBRARY})

# -------------------------------------------------------------------
# Install
# -------------------------------------------------------------------
set(ISAE_SLAM_LIBRARIES "${PROJECT_BINARY_DIR}/libisae_slam.so")

# Set the install path for the installed CeresConfig.cmake configuration file
# relative to CMAKE_INSTALL_PREFIX.
set(RELATIVE_CMAKECONFIG_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME})

install(
  TARGETS ${PROJECT_NAME}
  EXPORT ${PROJECT_NAME}Targets
  LIBRARY DESTINATION lib/${PROJECT_NAME}
  ARCHIVE DESTINATION lib/${PROJECT_NAME}
  RUNTIME DESTINATION bin/${PROJECT_NAME}
)
INSTALL (
    DIRECTORY ${CMAKE_SOURCE_DIR}/include/
    DESTINATION include
    FILES_MATCHING PATTERN "*.h*")
install(
  EXPORT ${PROJECT_NAME}Targets
  FILE ${PROJECT_NAME}Targets.cmake
  DESTINATION ${RELATIVE_CMAKECONFIG_INSTALL_DIR}
)

include(CMakePackageConfigHelpers)
configure_package_config_file(
    Config.cmake.in
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    INSTALL_DESTINATION ${RELATIVE_CMAKECONFIG_INSTALL_DIR}
)

install(
    FILES "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    DESTINATION ${RELATIVE_CMAKECONFIG_INSTALL_DIR}
)

message(STATUS "CMAKE_INSTALL_LIBDIR: ${CMAKE_INSTALL_LIBDIR}")
message(STATUS "${PROJECT_NAME}_BINARY_DIR: ${${PROJECT_NAME}_BINARY_DIR}")
message(STATUS "RELATIVE_CMAKECONFIG_INSTALL_DIR: ${RELATIVE_CMAKECONFIG_INSTALL_DIR}")

# Install the configuration files into the same directory as the autogenerated
# CeresTargets.cmake file.  We include the find_package() scripts for libraries
# whose headers are included in the public API of Ceres and should thus be
# present in CERES_INCLUDE_DIRS.
# install(FILES "${${PROJECT_NAME}_BINARY_DIR}/${PROJECT_NAME}Config-install.cmake"
#         RENAME ${PROJECT_NAME}Config.cmake
#         DESTINATION ${RELATIVE_CMAKECONFIG_INSTALL_DIR})
# install(FILES "${${PROJECT_NAME}_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake"
#         DESTINATION ${RELATIVE_CMAKECONFIG_INSTALL_DIR})

# -------------------------------------------------------------------
# Executables generation
# -------------------------------------------------------------------
add_executable(isaeslam ./main.cpp)
target_link_libraries(isaeslam ${PROJECT_NAME})

# -------------------------------------------------------------------
# Tests
# -------------------------------------------------------------------
option(ISAESLAM_BUILD_TESTS "Build tests" ON)

if(ISAESLAM_BUILD_TESTS)
  include(CTest)
  include(FetchContent)
  FetchContent_Declare(
    googletest
    URL https://github.com/google/googletest/archive/refs/heads/main.zip
  )
  find_package(GTest REQUIRED)
  enable_testing()

  add_executable(isae_test
    ./tests/association_test.cpp
    ./tests/basic_test.cpp
    ./tests/imu_test.cpp
    ./tests/linefeature_test.cpp
    ./tests/marginalization_test.cpp
    ./tests/mesh_test.cpp
    ./tests/nofov_test.cpp
    ./tests/residual_test.cpp
    ./tests/localmap_test.cpp)
  target_include_directories(isae_test PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
    $<INSTALL_INTERFACE:include>)
  target_link_libraries(isae_test
    GTest::gtest_main
    ${PROJECT_NAME}
  )

  include(GoogleTest)
  gtest_discover_tests(isae_test)
endif(ISAESLAM_BUILD_TESTS)

# -- debugging --
function(print_all_variables)
  message(STATUS "CMake Variables:")
  get_cmake_property(_variableNames CACHE_VARIABLES)
  list(SORT _variableNames)
  foreach (_variableName ${_variableNames})
    message(STATUS "${_variableName}=${${_variableName}}")
  endforeach()
endfunction()

print_all_variables()