services:
  sadvio:
    image: sadvio:jazzy
    container_name: sadvio
    build:
      context: ../../..
      dockerfile: SaDVIO/docker/jazzy/Dockerfile
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      #- RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - TERM
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:${XAUTHORITY}:ro
      - /dev:/dev:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/deos/s.jois/Execo/datasets:/datasets:ro
    entrypoint: /bin/bash
    command: ["-c", "sleep infinity"]
